#pragma once
#include <QObject>
#include "statemachine.h" // generated by qt_add_statecharts (defines StatemachineScxml class)
class MyModel;

class Statemachine : public QObject {
    Q_OBJECT
public:
    explicit Statemachine(MyModel *model, QObject *parent = nullptr);
    void start();
    Q_INVOKABLE void sendStart();
    Q_INVOKABLE void sendStop();
    Q_INVOKABLE void sendUpdate(int value);
private:
    statemachine m_scxml;
    MyModel *m_model;
};
